name: e-commerce-frontend CI
on:
  push:
  #   branches: [ main ]
  pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
          
      # Frontend
      - name: Frontend setup
        run: |
          npm install
          npm run build
    